language: php
php:
  - 7.0
  - 7.1
install:
  - pear install PHP_CodeSniffer
script:
  - phpenv rehash
  - phpcs .
  - docker run --rm -v $PWD:/app phpqa/security-checker security:check
notifications:
  email:
    recipients:
    - jeremyfs.moreau@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_AUTH
  app: indusiw1-jeremymoreau
  on:
    repo: JeremyFSMoreau/tp-indus-iw1